### ISSUE TITLE
"electron-webpack-ts": "^2.1.1"  not find

### ISSUE THREAD

**Issue by LeonWuV** [sitewhere/sitewhere-admin-ui#1]
when i input npm install after clone this repository， pop a tip said “No matching version found for electron-webpack-ts@2.1.1”

**Comment by derekadams** [comment]
Which version of Node.js and NPM are you using? We are not able to replicate the issue, but are happy to look into it if you have more information.

**Comment by LeonWuV** [comment]
Thanks，This is my information for nodejs & NPM ；
<img width="121" alt="20180921000242" src="https://user-images.githubusercontent.com/21948236/45831376-c02caa80-bd31-11e8-8543-772d8fe8600b.png">

By the way， The back end and data is ok,  I just need  to type 'npm install' & 'npm run dev' if I want to run this project，is that correct？

**Comment by LeonWuV** [comment]
thanks ，I already find the problem，  my npm‘s  registry is  ‘http://registry.npm.taobao.org/‘ not http://registry.npmjs.org，so I reset the registry;
