### ISSUE TITLE
Can the admin user interface run as a web application rather than an Electron app?

### ISSUE THREAD

**Issue by LeonWuV** [sitewhere/sitewhere-admin-ui#2]

**Comment by LeonWuV** [comment]
If it can do this ，please tell me how can I do？thanks！！

**Comment by derekadams** [comment]
What are you looking to do?

**Comment by LeonWuV** [comment]
Sorry, I missed a word.
This project can running in the browser ?

**Comment by LeonWuV** [comment]
I compared version 1.14 to version 2.0rc, which is basically the same, and I'm going to add webpack and same config files  to this project and turn it into a web application，like 1.14 version webpack config， is that right and success？

**Comment by derekadams** [comment]
We just transitioned the admin application from a web application to an Electron desktop app, so we do not plan to go back to the previous approach. We wanted to cleanly separate the administration app from the microservices. Is there a particular use case you are looking to solve by making it a web app? If you want to create a custom IoT application, the new application builder will be available for that.

**Comment by hongqizhang** [comment]
Is it possible to build the latest admin-ui in web application with Electron? I think it is fine to build an desktop app, however, it is better to build an web application at the same time with different package.json. Waiting for valuable points from you, thanks.
