### ISSUE TITLE
Operational issue

### ISSUE THREAD

**Issue by yuyewuye** [sitewhere/sitewhere-admin-ui#40]
Hi, I had some problems creating a project.
I selected Empty in the Dataset Template will cause many unexpected problems when i create a new tenant.But when i use "Construction"template ,it's good.
 Areas:I created a new area types ,when i created a areas with the area types ,the interface doesn't work.
Asset:I When I entered the Assets menu, I entered an Asset, but Assignments were all empty.
About Assignments:From V1.0 to V3.0,The system records each device reassignment, displays it in the same style and color code, and does not allow deletion of the history,It looks messy.Why not gray out the historical version and brighten up the latest allocation?

**Comment by derekadams** [comment]
Thanks for reporting the issues. Regarding assignments, with SiteWhere 3.0 a device can have multiple concurrent active assignments, but I agree that the user should be able to filter whether closed assignments are displayed. We will probably create separate issues for each of the above bugs and report on them separately to better track progress.

**Comment by derekadams** [comment]
Hi @yuyewuye I have not been able to reproduce the issues you had with using the `Empty` tenant. I was able to create the tenant, add a device, create an customer/area/asset and assign it to the device. Can you provide more detail on the issues you were seeing locally?

**Comment by derekadams** [comment]
Added issue for area boundaries bug: https://github.com/sitewhere/sitewhere-admin-ui/issues/41

**Comment by derekadams** [comment]
Added issue for bug listing zones for an area: https://github.com/sitewhere/sitewhere-admin-ui/issues/42

**Comment by derekadams** [comment]
Added issue for assignment list entry background color: https://github.com/sitewhere/sitewhere-admin-ui/issues/44
